<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="DESKTOP-F2GSG3S" failures="1" tests="3" name="com.E_GP.QA.BidderDatabase.TestCases.EquipmentsAddTest" time="37.327" errors="0" timestamp="22 Feb 2022 06:09:34 GMT" skipped="0">
  <testcase classname="com.E_GP.QA.BidderDatabase.TestCases.EquipmentsAddTest" name="equipmentsAddTest" time="13.556"/>
  <testcase classname="com.E_GP.QA.BidderDatabase.TestCases.EquipmentsAddTest" name="equipmentsAddTest" time="10.887">
    <failure message="expected [Equipment Information Saved Successfully.] but found [Equipment Save Successfully.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Equipment Information Saved Successfully.] but found [Equipment Save Successfully.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.E_GP.QA.Page.BidderDatabase.AddEquipments(BidderDatabase.java:924)
	at com.E_GP.QA.BidderDatabase.TestCases.EquipmentsAddTest.equipmentsAddTest(EquipmentsAddTest.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- equipmentsAddTest -->
  <testcase classname="com.E_GP.QA.BidderDatabase.TestCases.EquipmentsAddTest" name="equipmentsAddTest" time="12.884"/>
</testsuite> <!-- com.E_GP.QA.BidderDatabase.TestCases.EquipmentsAddTest -->
